### ISSUE TITLE
Error in UserManager.cs Constant STR_USERNAME_FORMAT

### ISSUE THREAD

**Issue by hsommer2** [DMIT-2018/DMIT-2018-StudentNotes#33]
The constant in the UserManager.cs file to give the username format has an error that results in the username being created as firstname.firstname instead of firstname.lastname. This is the line in the file.

// Requires FirstName and LastName
        private const string STR_USERNAME_FORMAT = "{0}.{0}";

This is what it should be:
// Requires FirstName and LastName
        private const string STR_USERNAME_FORMAT = "{0}.{1}";

**Comment by dwelchnait** [comment]
You do not need to add the code for generating the default users.

don

**Comment by dgilleland** [comment]
Old issue from previous semester
