### ISSUE TITLE
Results windows are in the incorrect place

### ISSUE THREAD

**Issue by brissonjess** [DMIT-2018/DMIT-2018-StudentNotes#35]
Hey,
I was reading about Anonymous Types on the following page and I noticed that the results for example 1 and 2 are mixed up. They employee result window is where the food window should be and vise versa with the food result window.
Cheers
http://dmit-2018.github.io/demos/docs/demos/eRestaurant/linq/index.html

**Comment by dgilleland** [comment]
Thanks @brissonjess ! :+1:
